version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URI=${DATABASE_URI}
