version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URI=${DATABASE_URI}
    depends_on:
      - database

  database:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db